version: '2'

services:
  nginx:
    image: autopilotpattern/nginx-example:branch-master
    mem_limit: 128m
    environment:
      - CONSUL_AGENT=1
      - CONSUL=localhost
    ports:
      - 80:80
    logging:
      driver: awslogs
      options:
        awslogs-group: autonginx
        awslogs-region: ap-southeast-2
        awslogs-stream-prefix: nginx

  backend:
    image: autopilotpattern/nginx-backend:branch-master
    mem_limit: 128m
    environment:
      - CONSUL=localhost
    ports:
    - 3001:3001
    logging:
      driver: awslogs
      options:
        awslogs-group: autonginx
        awslogs-region: ap-southeast-2
        awslogs-stream-prefix: backend


  consul:
    image: autopilotpattern/consul:branch-master
    environment:
      - CONSUL=localhost
      - CONSUL_DEV=dev
    command: >
      /usr/local/bin/containerpilot
    mem_limit: 128m
    ports:
      - 8500:8500
    logging:
      driver: awslogs
      options:
        awslogs-group: autonginx
        awslogs-region: ap-southeast-2
        awslogs-stream-prefix: consul